### ISSUE TITLE
Ääkköset pielessä Mac-käännössä

### ISSUE THREAD

**Issue by tuomassalo** [thelineva/tilitin#1]
Kun käänsin Tilittimen Macilla, ääkkösten tilalla oli neliöjuuren merkkiä yms. Näyttäisi korjaantuvan lisäämällä build.xml:ään encoding-attribuutti:

`<javac srcdir="${src}" destdir="${build}" classpath="${lib}/itext.jar" encoding="UTF-8"/>`

**Comment by thelineva** [comment]
Korjattu.
